plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group 'de.eugenbernwald'
version '1.0-SNAPSHOT'

javafx {
    version = "25"
    modules = [
            'javafx.controls',
            'javafx.fxml',
            'javafx.media'
    ]
}

application {
    mainClass = 'de.eugenbernwald.fretboardtrainer.FretboardTrainerApp'
    applicationDefaultJvmArgs = [
            '--enable-native-access', 'javafx.graphics'
    ]
}

repositories {
    mavenCentral()
    maven {
        url = "https://mvn.0110.be/releases"
    }
}

dependencies {
    implementation 'be.tarsos.dsp:core:2.5'
    implementation 'be.tarsos.dsp:jvm:2.5'
}
